### ISSUE TITLE
Missing source file for Database.Hedsql.Common.PrettyPrint

### ISSUE THREAD

**Issue by mgajda** [momomimachli/Hedsql#1]
I tried to compile your module today, and it seems that repo misses an essential input file: ```Database.Hedsql.Common.PrettyPrint```.

Is it in some other module, or just that you forgot to put it in?

**Comment by momomimachli** [comment]
Forgot it in the commits... It's fixed now.
You might be disappointed by what you'll find in that file. It's just a re-export of a pretty print library (it allows me to change pretty print library whenever needed, without changing the imports of other modules).

I've also corrected a bug in the test suit.
I'll close the issue. If anything else, don't hesitate.

**Comment by mgajda** [comment]
Thanks a lot!
